apiVersion: v1
kind: Service
metadata:
  name: hello-tencent
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 1984
  selector:
    app: hello-tencent
  type: LoadBalancer
